name: s1_coherence
channels:
  - conda-forge
dependencies:
  - python=>3.11 # required for shapely 2.0.0
  - asf_search
  - boto3
  - flake8
  - flake8-blind-except
  - flake8-builtins
  - flake8-import-order
  - geopandas
  - importlib_metadata
  - ipykernel
  - ipympl
  - jupyter
  - jupyterlab
  - jupytext
  - matplotlib
  - numpy
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - rasterio
  - requests
  - setuptools
  - setuptools_scm
  - shapely=>2.0
  - tqdm
  - wheel
  - pip:
      - tile-mate
